apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: kibana-config
data:
  kibana.yml: |-
    server.host: 127.0.0.1
    elasticsearch.hosts: http://elasticsearch-0.elasticsearch-svc:9200
---
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: kibana-svc
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - nodePort: 30602 # 3000 ~ 32767
    port: 5601
    targetPort: kibana-port
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: elk
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:7.10.2
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        ports:
        - containerPort: 5601
          name: kibana-port
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
          readOnly: true
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config
          items:
          - key: kibana.yml
            path: kibana.yml